apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-server3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gabletest/echo-k8s-app/
    targetRevision: HEAD
    path: kubernetes
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: echo-server3
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
